- name: create ec2 and route53
  hosts: local
  connection: local
  vars:
    ami_id: 
    sg_id:
    zone_id: 
    DOMAIN_NAME: "devopslearn.shop"
    instance:
    - mongodb
    - catalogue
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sq_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}" 
    loop: "{{ instances }}"
    register: ec2_output

    - name: print the ec2_output
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"