- name: setup rabbitmq server
  hosts: rabbitmq
  become: yes
  tasks:
  - name: copy the rabbitmq repo
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: install the rabbitmq package
    ansible.builtin.package:
      name: rabbitmq-server 
      state: present

  - name: create and provide permissions to add_user
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      permissions:
        - vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
      state: present

  - name: Start and enable service
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes

  
