- name: setup shipping server
  hosts: frontend
  become: yes
  tasks:
  - name: install maven and mysql
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql

  - name: install mysql python libraries
    ansible.builtin.pip:
      executable: pip3.9  
      name: "{{ item }}"
    loop:
    - cryptography
    - PyMySQL
    
  - name: create the roboshop system user
    ansible.builtin.user:
      name: roboshop
      system: true
      comment: roboshop system user
      shell: /sbin/nologin
      home: /app

  - name: remove the directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create the directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Delete shipping file
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent
  
  - name: download the shipping application file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
      dest: /tmp/shipping.zip

  - name: extract the shipping application
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: move jar file   
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app #change directory and move the file

  - name: copy the shipping service file
    ansible.builtin.template:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: import shipping data into mysql
    community.mysql.mysql_db:
      state: import
      name: all
      login_host: mysql.devopslearn.shop
      login_user: root
      login_password: RoboShop@1
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql

  - name: daemon reload enable and start the shipping
    ansible.builtin.service:
      name: shipping
      enabled: true
      state: restarted
      daemon_reload: true