- name: configure payment server
  hosts: payment
  become: yes
  tasks:
  - name: install python 
    ansible.builtin.dnf:
      name: "{{ item }}" 
      state: present
    loop:
    - python3
    - gcc
    - python3-devel
  
  - name: create the roboshop system user
    ansible.builtin.user:
      name: roboshop
      system: true
      comment: roboshop system user
      shell: /sbin/nologin
      home: /app

  - name: remove the directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create the directory
    ansible.builtin.file:
      path: /app
      state: directory 

  - name: delete the payment file
    ansible.builtin.file:
      path: /tmp/payment.zip
      state: absent

  - name: download the application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
      dest: /tmp/payment.zip

  - name: extract the application
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes

  - name: install the requirements or dependencies
    ansible.builtin.pip: 
      requirements: requirements.txt
      executable: pip3.9
    args:
      chdir: /app

  - name: copy the service file
    ansible.builtin.copy:
      name: payment.service
      dest: /etc/systemd/system/payment.service

  - name: daemon reload start and enable the payment
    ansible.builtin.systemd_service:
      name: payment
      enabled: true
      state: started
      daemon_reload: true